### ISSUE TITLE
GPGME::Error::InvalidValue: GPGME::Error::InvalidValue

### ISSUE THREAD

**Issue by mlagas** [ueno/ruby-gpgme#47]
Hello,

I've been trying to encrypt a data and it seem to work well on my local machine, however when I've deployed it on our server, it keeps on raising this error even with the simplest way of encrypting my data. Has anyone encountered this issue?  

```
e.g. crypto = GPGME::Crypto.new
      crypto.encrypt "The quick brown fox", :always_trust => true
```

This always raises this error "GPGME::Error::InvalidValue: GPGME::Error::InvalidValue".

**Comment by colto** [comment]
@mlagas I am running into the same things here, how did you change the permissions to fix your issue? This is driving me crazy.

**Comment by bbozo** [comment]
@colto @mlagas what did you do to fix the permissions???? :) production breaking, grr, help please :)

**Comment by bbozo** [comment]
Thing is, I had to import the keys manually, for whatever reason they were not ending up in the keyring. And for the "name" use the name from the GPG cert that I saw once I did `gpg --import key_path`, then everything worked

Seriously irritated by GPG's stubborn insistence on the keyring and the way it behaves differently from host to host, from key to key

**Comment by bbozo** [comment]
Aaaand, I would like to take this moment to reiterate how much I hate GPG as a programming SDK facilitator, it literally never so far behaved the same on 2 different VMs for the purpose of solving the problem of "encrypt file with this key"

this time the issue was that the issues of the PGP key could not be confirmed by the web-of-trust thingy, whatever it is http://askubuntu.com/a/523228/468618

But... still not resolved :-/ this is the debug trace, showing both the successful local execution and the failed execution in production: https://gist.github.com/bbozo/3d8a7fd5f04babb3f08314f9b7d4e491

The production trace is with `gpg (GnuPG) 1.4.20`, the exactly same source code depending on `gpg (GnuPG) 1.4.18` works on my dev box.

This command works on both boxes:

```
/usr/bin/gpg1  --output ./test_file.txt.pgp --encrypt --recipient dcapci test_file.txt
```

Any ideas what might be going wrong? :-/

**Comment by ueno** [comment]
In https://gist.github.com/bbozo/3d8a7fd5f04babb3f08314f9b7d4e491, I see --homedir points to /home/webteh.  That means gpg will look for the keys under /home/webteh, rather than /home/webteh/.gnupg.  Is it intentional?
```
GPGME 2016-11-08 11:53:58 <0x7a25>    _gpgme_io_spawn: check: path=0x658f330, argv[ 3] = --homedir
GPGME 2016-11-08 11:53:58 <0x7a25> _gpgme_io_spawn: check: path=0x658f330, argv[ 4] = /home/webteh
```

**Comment by bbozo** [comment]
@ueno wowwww, that solved it, `set_engine` parameter homedir is homedir of GnuPG, not of the user ^_^ thank you very very much, I am in your debt dear sir
